# Generated by Django 6.0.6 on 2026-07-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название продукта')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='image/product', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
